routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
	Route::get('/', 'DashboardController@dashboard')->name('admin.index');
	Route::resource('/category', 'CategoryController', ['as'=>'admin']);
	Route::resource('/article', 'ArticleController', ['as'=>'admin']);
	Route::get('/image/create', 'ImageController@create')->name('image.create');
    Route::post('/image/upload', 'ImageController@upload')->name('image.upload');
	Route::group(['prefix'=>'user_management', 'namespace'=>'UserManagement'], function(){
		Route::resource('/user', 'UserController', ['as'=>'admin.user_management']);
	});
  Route::get('/tb', 'TelbotController@index')->name('admin.tb');
  Route::get('/setting', 'SettingController@index')->name('setting.index');
  Route::post('/setting/store', 'SettingController@store')->name('setting.store');
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::match(['post', 'get'], 'register', function(){
  Auth::logout();
  return redirect('/');
})->name('register');

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function users_additional()
    {
        return $this->hasOne('App\UserAdditional');
    }
}

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user_management.users.index', [
            'users' => User::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_management.users.create', [
            'user' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        User::create([
                'name' => $request['name'],
                'email' => $request['email'],
                'password' => bcrypt($request['password'])
            ]);

        return redirect()->route('admin.user_management.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
         return view('admin.user_management.users.edit', [
                'user' => $user
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => ['required', 'string', 'email', 'max:255', \Illuminate\Validation\Rule::unique('users')->ignore($user->id)],
            'password' => 'nullable|string|min:6|confirmed',
        ]);

        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->save();  

        return redirect()->route('admin.user_management.user.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('admin.user_management.user.index');
    }
}

resources/views/admin/user_management/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Create of user @endslot
	@slot('parent') Dashboard @endslot
	@slot('active') Users @endslot
	@endcomponent
	<hr>
	<form action="{{ route('admin.user_management.user.store') }}" method="post" class="form-horizontal">
		{{ csrf_field() }}
		@include('admin.user_management.users.partials.form')
	</form>
</div>
@endsection

resources/views/admin/user_management/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Edit of User @endslot
	@slot('parent') Dashboard @endslot
	@slot('active') Users @endslot
	@endcomponent
	<hr>
	<form action="{{ route('admin.user_management.user.update', $user) }}" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="put">
		{{ csrf_field() }}
    @include('admin.user_management.users.partials.form')
	</form>
</div>
@endsection

resources/views/admin/user_management/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') User List @endslot
	@slot('parent') Dashboard @endslot
	@slot('active') Userss @endslot
	@endcomponent
	<hr>
	<a href="{{ route('admin.user_management.user.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"> Create User</i></a>
	<table class="table table-striped">
		<thead>
			<th>Name</th>
			<th>Email</th>
			<th class="text-right">Action</th>
		</thead>
		<tbody>
			@forelse($users as $user)
            <tr>
            	<td>{{ $user->name }}</td>
            	<td>{{ $user->email }}</td> 
            	<td class="text-right">
            		<form action="{{ route('admin.user_management.user.destroy', $user) }}" onsubmit="if(confirm('Delete?')){return true}else{return false}" method="post">
            			<input type="hidden" name="_method" value="DELETE"> 
            			{{ csrf_field() }}
            			<a href="{{ route('admin.user_management.user.edit', $user) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
            			<button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
            		</form></td>
            </tr>
			@empty
            <tr>
            	<td colspan="3" class="text-center"><h2>No user</h2></td>
            </tr>
			@endforelse
			<tfoot>
				<tr>
					<td colspam="3">
						<ul class="pagination pull-right">
							{{ $users->links() }} 
						</ul>
					</td>
				</tr>
			</tfoot>
		</tbody>
	</table>
</div>
@endsection