routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
	Route::get('/', 'DashboardController@dashboard')->name('admin.index');
	Route::resource('/category', 'CategoryController', ['as'=>'admin']);
	Route::resource('/article', 'ArticleController', ['as'=>'admin']);
	Route::get('/image/create', 'ImageController@create')->name('image.create');
    Route::post('/image/upload', 'ImageController@upload')->name('image.upload');
	Route::group(['prefix'=>'user_management', 'namespace'=>'UserManagement'], function(){
		Route::resource('/user', 'UserController', ['as'=>'admin.user_management']);
	});
  Route::get('/tb', 'TelbotController@index')->name('admin.tb');
  Route::get('/setting', 'SettingController@index')->name('setting.index');
  Route::post('/setting/store', 'SettingController@store')->name('setting.store');
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::match(['post', 'get'], 'register', function(){
  Auth::logout();
  return redirect('/');
})->name('register');

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{

    protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title', 'meta_description', 'meta_keyword', 'published', 'created_by', 'modified_by'];

    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . '-' . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    public function categories()
    {
    	return $this->morphToMany('App\Category', 'categoryable');
    }

    public function scopeLatestArticles($query, $count)
    {
    	return $query->orderBy('created_at', 'desc')->take($count)->get();
    }

    public function scopePuplished($query, $published)
    {
        return $query->where('published', $published)->take(5);
    }

    public function orderByCreated($query)
    {
        return $query->orderBy('created_at');
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
            'articles' => Article::orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create', [
            'article' => [],
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = Article::create($request->all());

        if($request->input('categories')){
            $article->categories()->attach($request->input('categories'));
        }

        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
            'article' => $article,
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update(except('slug'));

        $article->categories()->detach();

        if($request->input('categories')){
            $article->categories()->attach($request->input('categories'));
        }

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->categories()->detach();
        $article->delete();

        return redirect()->route('admin.article.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Create of Article @endslot
	@slot('parent') Dashboard @endslot
	@slot('active') Articles @endslot
	@endcomponent
	<hr>
	<form action="{{ route('admin.article.store') }}" method="post" class="form-horizontal">
		{{ csrf_field() }}
		@include('admin.articles.partials.form')
		<input type="hidden" name="created_by" value="{{Auth::id()}}">
	</form>
</div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') Edit of Article @endslot
	@slot('parent') Dashboard @endslot
	@slot('active') Articles @endslot
	@endcomponent
	<hr>
	<form action="{{ route('admin.article.update', $article) }}" method="post" class="form-horizontal">
		<input type="hidden" name="_method" value="put">
		{{ csrf_field() }}
		<label for="">Status</label>
<select name="published" id="" class="form-control"> 
@if(isset($article['id']))
    <option value="0" @if($article['published'] == 0) selected @endif>Not published</option>
    <option value="1" @if($article['published'] == 1) selected @endif>Published</option>
@else
    <option value="0">Not published</option>
    <option value="1">Published</option>
@endif
</select>

<label for="">Title</label>
<input type="text" class="form-control" name="title" placeholder="title" value="{{ $article['title'] or '' }}" required>

<label for="">Slug</label>
<input type="text" class="form-control" name="slug" placeholder="Automatic Generation" value="{{ $article['slug'] or '' }}" readonly="">  

<label for="">Category</label>
<select name="categories[]" id="" class="form-control" multiple="">
	<option value="0">--Without Category--</option>
	@foreach ($categories as $category)

  <option value="{{$category->id or ""}}"

    @isset($article['id'])
      @foreach ($article['categories'] as $category_article)
        @if ($category->id == $category_article)
          selected="selected"
        @endif
      @endforeach
    @endisset

    >
    {!! $delimiter or "" !!}{{$category->title or ""}}
  </option>

  @if (count($category->children) > 0)

    @include('admin.articles.partials.categories', [
      'categories' => $category->children,
      'delimiter'  => ' - ' . $delimiter
    ])

  @endif
@endforeach
</select>

<label for="description-short">Short Description</label>
<textarea name="description_short" id="description-short" cols="30" rows="10" class="form-control">{{ $article['description_short'] or '' }}</textarea>


<label for="description">Description</label>
<textarea name="description" id="description" cols="30" rows="10" class="form-control">{{ $article['description'] or '' }}</textarea>
<script type="text/javascript">
$(document).ready(function(){
    CKEDITOR.replace( 'description-short' );
    CKEDITOR.replace( 'description' );
});
 </script>

<label for="meta_title">Meta Title</label>
<input type="text" name="meta_title" id="meta_title" cols="30" rows="10" class="form-control" value="{{ $article['meta_title'] or '' }}">

<label for="meta_description">Meta description</label>
<input type="text" name="meta_description" id="meta_description" cols="30" rows="10" class="form-control" value="{{ $article['meta_description'] or '' }}">

<label for="keywords">Keywords</label>
<input type="text" name="meta_keyword" id="keywords" cols="30" rows="10" class="form-control" value="{{ $article['keyword'] or '' }}">
<hr>
<input type="submit" name="some_name" class="btn btn-primary" value="save">

  
		<input type="hidden" name="modified_by" value="{{Auth::id()}}">
	</form>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">
	@component('admin.components.breadcrumb')
	@slot('title') List of articles @endslot
	@slot('parent') Main page @endslot
	@slot('active') Articles @endslot
	@endcomponent
	<hr/>
	<a href="{{ route('admin.article.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-square-o"> Create article</i></a>
	<table class="table table-striped">
		<thead>
			<th>Name</th>
			<th>Publish</th>
			<th class="text-right">Action</th>
		</thead>
		<tbody>
			@forelse($articles as $article)
			<tr>
				<td>{{ $article->title }}</td>
				<td>{{ $article->published }}</td>
				<td class="text-right">
				    <form action="{{ route('admin.article.destroy', $article) }}" onsubmit="if(confirm('Delete?')){return true}else{return false}" method="post">
            			<input type="hidden" name="_method" value="DELETE"> 
            			{{ csrf_field() }}
            			<a href="{{ route('admin.article.edit', $article) }}" class="btn btn-default"><i class="fa fa-edit"></i></a>
            			<button type="submit" class="btn"><i class="fa fa-trash-o"></i></button>
            		</form></td>
			</tr>
			@empty
			<tr>
				<td colspan="3" class="text-center">No articles</td>
			</tr>
			@endforelse
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3">
					<ul class="pagination full-right">
						{{ $articles->links() }}
					</ul>
				</td>
			</tr>
		</tfoot>
	</table>
</div>

@endsection